name = "clawcuts"
account_id = "b8f2c66f1848dff476faa874282d781e"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "clawcuts.com/*", zone_name = "clawcuts.com" },
  { pattern = "www.clawcuts.com/*", zone_name = "clawcuts.com" }
]

[[d1_databases]]
binding = "CUTS_DB"
database_name = "clawcuts"
database_id = "76418170-3b27-40d4-bfb1-5c29610e008e"

[vars]
CUTS_VERSION = "0.2.1"
CUTS_FEE_CLEARING_ACCOUNT = "clearing:clawcuts"

[env.staging]
name = "clawcuts-staging"
routes = [
  { pattern = "staging.clawcuts.com/*", zone_name = "clawcuts.com" }
]

[[env.staging.d1_databases]]
binding = "CUTS_DB"
database_name = "clawcuts-staging"
database_id = "3bda8020-7483-49e1-aacb-99e6eaea1592"

[env.staging.vars]
CUTS_VERSION = "0.2.1"
CUTS_FEE_CLEARING_ACCOUNT = "clearing:clawcuts"
