name = "clawledger-lite"
account_id = "b8f2c66f1848dff476faa874282d781e"
main = "src/index.ts"
compatibility_date = "2026-02-04"

routes = [
  { pattern = "usdc-testnet.clawledger.com/*", zone_name = "clawledger.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "clawledger-lite"
database_id = "053b33e7-0a5e-4bb6-aa08-cf782a3656ed"
